# Generated by Django 6.1.1 on 2026-09-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('fruit', 'Fruit'), ('legume', 'Légume'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('produit_laitier', 'Produit laitier'), ('epicerie', 'Épicerie'), ('boisson', 'Boisson'), ('boulangerie', 'Boulangerie'), ('confiserie', 'Confiserie'), ('autre', 'Autre')], max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gramme', models.IntegerField(blank=True, null=True)),
                ('prixkg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prixlitre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_peremption', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('nutriscore', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('bio', models.BooleanField(default=False)),
                ('label_rouge', models.BooleanField(default=False)),
                ('aop', models.BooleanField(default=False)),
                ('igp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContenuFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
